// software/ai-pendant-dashboard/app/login/page.tsx
type LoginPageProps = {
  searchParams?: Promise<{
    error?: string;
    returnTo?: string;
  }>;
};

export const dynamic = "force-dynamic";

export default async function LoginPage({ searchParams }: LoginPageProps) {
  const params = (await searchParams) ?? {};
  const returnTo =
    params.returnTo?.startsWith("/") && !params.returnTo.startsWith("//")
      ? params.returnTo
      : "/";

  return (
    <main className="login-shell">
      <section className="login-card" aria-labelledby="login-title">
        <div className="brand-mark" aria-hidden="true">
          P
        </div>
        <p className="kicker">AI Pendant</p>
        <h1 id="login-title">Dashboard</h1>
        <p className="login-copy">Enter your pairing code.</p>

        {params.error ? (
          <p className="login-error" role="alert">
            That pairing code was not accepted.
          </p>
        ) : null}

        <form className="login-form" action="/api/auth/login" method="post">
          <input type="hidden" name="returnTo" value={returnTo} />
          <label htmlFor="accessKey">Pairing code</label>
          <input
            id="accessKey"
            name="accessKey"
            type="password"
            autoComplete="current-password"
            required
            autoFocus
          />
          <button type="submit">Continue</button>
        </form>
        <p className="login-note">
          Your code is sent only to the dashboard over HTTPS and never appears
          in the page URL.
        </p>
      </section>
    </main>
  );
}

// software/dashboard-sveltekit/src/routes/login/+page.svelte
<script lang="ts">
  import { page } from "$app/state";

  // The server's `safeReturnTo` still governs where the 303 actually lands;
  // this is only the value echoed back into the form.
  const returnTo = $derived.by(() => {
    const raw = page.url.searchParams.get("returnTo") ?? "";
    return raw.startsWith("/") && !raw.startsWith("//") ? raw : "/";
  });
  const failed = $derived(Boolean(page.url.searchParams.get("error")));
</script>

<main class="login-shell">
  <section class="login-card" aria-labelledby="login-title">
    <div class="brand-mark" aria-hidden="true">P</div>
    <p class="kicker">AI Pendant</p>
    <h1 id="login-title">Dashboard</h1>
    <p class="login-copy">Enter your pairing code.</p>

    {#if failed}
      <p class="login-error" role="alert">
        That pairing code was not accepted.
      </p>
    {/if}

    <!-- A native form post, so signing in works before (and without) hydration. -->
    <form class="login-form" action="/api/auth/login" method="post">
      <input type="hidden" name="returnTo" value={returnTo} />
      <label for="accessKey">Pairing code</label>
      <!-- svelte-ignore a11y_autofocus -->
      <input
        id="accessKey"
        name="accessKey"
        type="password"
        autocomplete="current-password"
        required
        autofocus
      />
      <button type="submit">Continue</button>
    </form>
    <p class="login-note">
      Your code is sent only to the dashboard over HTTPS and never appears in
      the page URL.
    </p>
  </section>
</main>
